<div class="jumbotron">
    <form>
    <h1>Bienvenido a <span class="zf-green">ZF Movies</span></h1>

    <p>
        Elige tu género de películas favorito:
        <select>
            <option>----</option>
            <option value="comedia">Comedia</option>
            <option value="cienciaFiccion">Ciencia Ficción</option>
            <option value="accion">Acción</option>
            <option value="terror">Terror</option>
        </select>
    </p>


    <p><input type="submit" class="btn btn-success btn-lg" id="button-select" value="Elegir &raquo;"></input></p>
    </form>
</div>

<div class="row">
<?php
// list movies here
?>
</div>
